### ISSUE TITLE
IE  gives syntax error in md5js first line

### ISSUE THREAD

**Issue by aeternusinfernus** [xibre/FastMD5#5]
the md5.js gives a syntax error in IE
line: 1, column: 1

Any idea?

**Comment by iReal** [comment]
@aeternusinfernus what IE version are you using?

**Comment by aeternusinfernus** [comment]
@iReal My apologies, at first it was in IE10, but it seems I can't reproduce the error any more. 

just wondering the file hash example you gave. Is there a change that it will display an incorrect hash? The tests I did on files seems to produce correct values. Just wondering though if I can rely on it. Thanks for all your work !

**Comment by iReal** [comment]
@aeternusinfernus Current implementation works well with any data you put in. However, it seems to be incorrect in some older IE versions. Also, it isn't designed to handle really large files incrementally.
I'll take care of these issues in a second release.

**Comment by aeternusinfernus** [comment]
@iReal , Thanks for this! It really works nicely!
you mean lower versions than IE 10 right (9,8,7 etc)? As far as I  know lower versions than 10 do not support the FileAPI so that would explain that (http://caniuse.com/#feat=fileapi). Or do you mean subversions within IE10. I'm getting good results in IE 10 and 11 as we speak. Cheers for the work!

**Comment by iReal** [comment]
@aeternusinfernus
https://github.com/wbond/md5-js/blob/master/md5.js#L166-L179 that's the issue. It seems that we can't add two numbers modulo 2^32 that way. It will fail in some IE's lower than IE8 (or maybe even lower, haven't tested that yet).

Anyway, if you're going to hash file contents only, the FileAPI is required. So, as long as your browser supports FileAPI, everything should work just fine.

**Comment by aeternusinfernus** [comment]
@iReal, great than we think alike :) Thanks for the heads up!
